//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	// Read the protocol file
	protocolPath := "../../_rules/AGENTS.md.protocol"
	content, err := os.ReadFile(protocolPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading protocol file: %v\n", err)
		os.Exit(1)
	}

	// Escape backticks for Go raw string literal
	// We'll replace ` with ` + "`" + ` to break the string literal
	escapedContent := strings.ReplaceAll(string(content), "`", "` + \"`\" + `")

	// Create the generated file content
	generatedContent := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
package main

const AgentProtocol = `+"`%s`"+`
`,
	escapedContent)

	// Write to protocol_content.go
	outputPath := "protocol_content.go"
	if err := os.WriteFile(outputPath, []byte(generatedContent), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing generated file: %v\n", err)
		os.Exit(1)
	}

	// Get absolute path for logging
	absPath, _ := filepath.Abs(protocolPath)
	fmt.Printf("Successfully generated %s from %s\n", outputPath, absPath)
}
